import { WizardContent } from './components';
import { getTranslations } from '@/i18n/server';
import styles from './page.module.css';

export default async function AIContentWizardPage() {
  const t = await getTranslations();

  const translations = {
    // Step names
    steps: {
      campaign: t('aiWizard.steps.campaign'),
      postCount: t('aiWizard.steps.postCount'),
      schedule: t('aiWizard.steps.schedule'),
      articleTypes: t('aiWizard.steps.articleTypes'),
      contentSettings: t('aiWizard.steps.contentSettings'),
      subjects: t('aiWizard.steps.subjects'),
      keywords: t('aiWizard.steps.keywords'),
      prompts: t('aiWizard.steps.prompts'),
      summary: t('aiWizard.steps.summary'),
    },
    // WP Gate
    wpRequired: {
      title: t('aiWizard.wpRequired.title'),
      description: t('aiWizard.wpRequired.description'),
      notWordpress: t('aiWizard.wpRequired.notWordpress'),
      notConnected: t('aiWizard.wpRequired.notConnected'),
    },
    // Campaign step
    campaign: {
      title: t('aiWizard.campaign.title'),
      description: t('aiWizard.campaign.description'),
      selectExisting: t('aiWizard.campaign.selectExisting'),
      createNew: t('aiWizard.campaign.createNew'),
      noCampaigns: t('aiWizard.campaign.noCampaigns'),
      nameLabel: t('aiWizard.campaign.nameLabel'),
      namePlaceholder: t('aiWizard.campaign.namePlaceholder'),
      colorLabel: t('aiWizard.campaign.colorLabel'),
      reservedColor: t('aiWizard.campaign.reservedColor'),
      editCampaign: t('aiWizard.campaign.editCampaign'),
      deleteCampaign: t('aiWizard.campaign.deleteCampaign'),
      deleteConfirm: t('aiWizard.campaign.deleteConfirm'),
      cancelDelete: t('aiWizard.campaign.cancelDelete'),
      nameRequired: t('aiWizard.campaign.nameRequired'),
      selectOrCreateError: t('aiWizard.campaign.selectOrCreateError'),
      createError: t('aiWizard.campaign.createError'),
      existingCampaigns: t('aiWizard.campaign.existingCampaigns'),
    },
    // Post count step
    postCount: {
      title: t('aiWizard.postCount.title'),
      description: t('aiWizard.postCount.description'),
      label: t('aiWizard.postCount.label'),
      hint: t('aiWizard.postCount.hint'),
    },
    // Schedule step
    schedule: {
      title: t('aiWizard.schedule.title'),
      description: t('aiWizard.schedule.description'),
      startDate: t('aiWizard.schedule.startDate'),
      endDate: t('aiWizard.schedule.endDate'),
      selectDate: t('aiWizard.schedule.selectDate'),
      clearSelection: t('aiWizard.schedule.clearSelection'),
      publishDays: t('aiWizard.schedule.publishDays'),
      publishDaysHint: t('aiWizard.schedule.publishDaysHint'),
      days: {
        sun: t('aiWizard.schedule.days.sun'),
        mon: t('aiWizard.schedule.days.mon'),
        tue: t('aiWizard.schedule.days.tue'),
        wed: t('aiWizard.schedule.days.wed'),
        thu: t('aiWizard.schedule.days.thu'),
        fri: t('aiWizard.schedule.days.fri'),
        sat: t('aiWizard.schedule.days.sat'),
      },
      daysFull: {
        sun: t('aiWizard.schedule.daysFull.sun'),
        mon: t('aiWizard.schedule.daysFull.mon'),
        tue: t('aiWizard.schedule.daysFull.tue'),
        wed: t('aiWizard.schedule.daysFull.wed'),
        thu: t('aiWizard.schedule.daysFull.thu'),
        fri: t('aiWizard.schedule.daysFull.fri'),
        sat: t('aiWizard.schedule.daysFull.sat'),
      },
      publishTime: t('aiWizard.schedule.publishTime'),
      randomTime: t('aiWizard.schedule.randomTime'),
      fixedTime: t('aiWizard.schedule.fixedTime'),
      fixedTimeLabel: t('aiWizard.schedule.fixedTimeLabel'),
      timeStart: t('aiWizard.schedule.timeStart'),
      timeEnd: t('aiWizard.schedule.timeEnd'),
      randomHint: t('aiWizard.schedule.randomHint'),
      morePosts: t('aiWizard.schedule.morePosts'),
      fewerPosts: t('aiWizard.schedule.fewerPosts'),
      gotIt: t('aiWizard.schedule.gotIt'),
    },
    months: [
      t('aiWizard.schedule.months.0'),
      t('aiWizard.schedule.months.1'),
      t('aiWizard.schedule.months.2'),
      t('aiWizard.schedule.months.3'),
      t('aiWizard.schedule.months.4'),
      t('aiWizard.schedule.months.5'),
      t('aiWizard.schedule.months.6'),
      t('aiWizard.schedule.months.7'),
      t('aiWizard.schedule.months.8'),
      t('aiWizard.schedule.months.9'),
      t('aiWizard.schedule.months.10'),
      t('aiWizard.schedule.months.11'),
    ],
    dayNames: [
      t('time.sun'), t('time.mon'), t('time.tue'), t('time.wed'),
      t('time.thu'), t('time.fri'), t('time.sat'),
    ],
    // Article types step
    articleTypes: {
      title: t('aiWizard.articleTypes.title'),
      description: t('aiWizard.articleTypes.description'),
      types: {
        seo: {
          label: t('aiWizard.articleTypes.types.seo.label'),
          description: t('aiWizard.articleTypes.types.seo.description'),
          example: t('aiWizard.articleTypes.types.seo.example'),
        },
        blogPost: {
          label: t('aiWizard.articleTypes.types.blogPost.label'),
          description: t('aiWizard.articleTypes.types.blogPost.description'),
          example: t('aiWizard.articleTypes.types.blogPost.example'),
        },
        guide: {
          label: t('aiWizard.articleTypes.types.guide.label'),
          description: t('aiWizard.articleTypes.types.guide.description'),
          example: t('aiWizard.articleTypes.types.guide.example'),
        },
        howTo: {
          label: t('aiWizard.articleTypes.types.howTo.label'),
          description: t('aiWizard.articleTypes.types.howTo.description'),
          example: t('aiWizard.articleTypes.types.howTo.example'),
        },
        listicle: {
          label: t('aiWizard.articleTypes.types.listicle.label'),
          description: t('aiWizard.articleTypes.types.listicle.description'),
          example: t('aiWizard.articleTypes.types.listicle.example'),
        },
        comparison: {
          label: t('aiWizard.articleTypes.types.comparison.label'),
          description: t('aiWizard.articleTypes.types.comparison.description'),
          example: t('aiWizard.articleTypes.types.comparison.example'),
        },
        review: {
          label: t('aiWizard.articleTypes.types.review.label'),
          description: t('aiWizard.articleTypes.types.review.description'),
          example: t('aiWizard.articleTypes.types.review.example'),
        },
        news: {
          label: t('aiWizard.articleTypes.types.news.label'),
          description: t('aiWizard.articleTypes.types.news.description'),
          example: t('aiWizard.articleTypes.types.news.example'),
        },
        tutorial: {
          label: t('aiWizard.articleTypes.types.tutorial.label'),
          description: t('aiWizard.articleTypes.types.tutorial.description'),
          example: t('aiWizard.articleTypes.types.tutorial.example'),
        },
        caseStudy: {
          label: t('aiWizard.articleTypes.types.caseStudy.label'),
          description: t('aiWizard.articleTypes.types.caseStudy.description'),
          example: t('aiWizard.articleTypes.types.caseStudy.example'),
        },
      },
      wordRange: t('aiWizard.articleTypes.wordRange'),
      postsOfType: t('aiWizard.articleTypes.postsOfType'),
      total: t('aiWizard.articleTypes.total'),
      of: t('aiWizard.articleTypes.of'),
      whatIsThis: t('aiWizard.articleTypes.whatIsThis'),
      exampleLabel: t('aiWizard.articleTypes.exampleLabel'),
      wordRangeLabel: t('aiWizard.articleTypes.wordRangeLabel'),
      gotIt: t('aiWizard.articleTypes.gotIt'),
      unallocated: t('aiWizard.articleTypes.unallocated'),
      allocationError: t('aiWizard.articleTypes.allocationError'),
      maxTypesError: t('aiWizard.articleTypes.maxTypesError'),
    },
    // Content settings step
    contentSettings: {
      title: t('aiWizard.contentSettings.title'),
      description: t('aiWizard.contentSettings.description'),
      wordCountLabel: t('aiWizard.contentSettings.wordCountLabel'),
      recommended: t('aiWizard.contentSettings.recommended'),
      words: t('aiWizard.contentSettings.words'),
      featuredImage: t('aiWizard.contentSettings.featuredImage'),
      contentImages: t('aiWizard.contentSettings.contentImages'),
      contentImagesCount: t('aiWizard.contentSettings.contentImagesCount'),
      images: t('aiWizard.contentSettings.images'),
      hebrewSlug: t('aiWizard.contentSettings.hebrewSlug'),
      hebrewSlugHint: t('aiWizard.contentSettings.hebrewSlugHint'),
      metaTitle: t('aiWizard.contentSettings.metaTitle'),
      metaDescription: t('aiWizard.contentSettings.metaDescription'),
      faq: t('aiWizard.contentSettings.faq'),
    },
    // Subjects step
    subjects: {
      title: t('aiWizard.subjects.title'),
      description: t('aiWizard.subjects.description'),
      generate: t('aiWizard.subjects.generate'),
      regenerate: t('aiWizard.subjects.regenerate'),
      generating: t('aiWizard.subjects.generating'),
      noKeywordsWarning: t('aiWizard.subjects.noKeywordsWarning'),
      errorGenerating: t('aiWizard.subjects.errorGenerating'),
      selectedCount: t('aiWizard.subjects.selectedCount'),
      addCustom: t('aiWizard.subjects.addCustom'),
      customPlaceholder: t('aiWizard.subjects.customPlaceholder'),
      explanationPlaceholder: t('aiWizard.subjects.explanationPlaceholder'),
      addSubject: t('aiWizard.subjects.addSubject'),
      custom: t('aiWizard.subjects.custom'),
      selectedSubjects: t('aiWizard.subjects.selectedSubjects'),
      allSelected: t('aiWizard.subjects.allSelected'),
      selectRemaining: t('aiWizard.subjects.selectRemaining'),
      onePerKeyword: t('aiWizard.subjects.onePerKeyword'),
      gotIt: t('aiWizard.subjects.gotIt'),
    },
    // Keywords step
    keywords: {
      title: t('aiWizard.keywords.title'),
      description: t('aiWizard.keywords.description'),
      selectFromList: t('aiWizard.keywords.selectFromList'),
      fromGSC: t('aiWizard.keywords.fromGSC'),
      addManual: t('aiWizard.keywords.addManual'),
      manualPlaceholder: t('aiWizard.keywords.manualPlaceholder'),
      selected: t('aiWizard.keywords.selected'),
      noKeywords: t('aiWizard.keywords.noKeywords'),
      noGSC: t('aiWizard.keywords.noGSC'),
      noGSCData: t('aiWizard.keywords.noGSCData'),
      noResults: t('aiWizard.keywords.noResults'),
      connectGSC: t('aiWizard.keywords.connectGSC'),
      searchPlaceholder: t('aiWizard.keywords.searchPlaceholder'),
      clicks: t('aiWizard.keywords.clicks'),
      impressions: t('aiWizard.keywords.impressions'),
      selectGSCSite: t('aiWizard.keywords.selectGSCSite'),
      selectGSCSiteDesc: t('aiWizard.keywords.selectGSCSiteDesc'),
      noGSCSites: t('aiWizard.keywords.noGSCSites'),
      permOwner: t('aiWizard.keywords.permOwner'),
      permFull: t('aiWizard.keywords.permFull'),
      permRestricted: t('aiWizard.keywords.permRestricted'),
      permUnverified: t('aiWizard.keywords.permUnverified'),
      domainProperty: t('aiWizard.keywords.domainProperty'),
      cancel: t('aiWizard.keywords.cancel'),
    },
    // Prompts step
    prompts: {
      title: t('aiWizard.prompts.title'),
      description: t('aiWizard.prompts.description'),
      textPromptLabel: t('aiWizard.prompts.textPromptLabel'),
      textPromptPlaceholder: t('aiWizard.prompts.textPromptPlaceholder'),
      textPromptHint: t('aiWizard.prompts.textPromptHint'),
      imagePromptLabel: t('aiWizard.prompts.imagePromptLabel'),
      imagePromptPlaceholder: t('aiWizard.prompts.imagePromptPlaceholder'),
      imagePromptHint: t('aiWizard.prompts.imagePromptHint'),
    },
    // Summary step
    summary: {
      title: t('aiWizard.summary.title'),
      description: t('aiWizard.summary.description'),
      campaignName: t('aiWizard.summary.campaignName'),
      totalPosts: t('aiWizard.summary.totalPosts'),
      dateRange: t('aiWizard.summary.dateRange'),
      publishDays: t('aiWizard.summary.publishDays'),
      publishTime: t('aiWizard.summary.publishTime'),
      articleTypes: t('aiWizard.summary.articleTypes'),
      keywords: t('aiWizard.summary.keywords'),
      plannedPosts: t('aiWizard.summary.plannedPosts'),
      generatePlan: t('aiWizard.summary.generatePlan'),
      generatingPlan: t('aiWizard.summary.generatingPlan'),
      postTitle: t('aiWizard.summary.postTitle'),
      postType: t('aiWizard.summary.postType'),
      postDate: t('aiWizard.summary.postDate'),
      postKeyword: t('aiWizard.summary.postKeyword'),
      postSubject: t('aiWizard.summary.postSubject'),
      editTitle: t('aiWizard.summary.editTitle'),
      noSubject: t('aiWizard.summary.noSubject'),
      noKeyword: t('aiWizard.summary.noKeyword'),
      expandAll: t('aiWizard.summary.expandAll'),
      collapseAll: t('aiWizard.summary.collapseAll'),
      random: t('aiWizard.summary.random'),
      fixed: t('aiWizard.summary.fixed'),
      subjectsTitle: t('aiWizard.summary.subjectsTitle'),
      explanation: t('aiWizard.summary.explanation'),
      wordCount: t('aiWizard.summary.wordCount'),
      words: t('aiWizard.summary.words'),
      custom: t('aiWizard.summary.custom'),
      existingPosts: t('aiWizard.summary.existingPosts'),
      otherCampaigns: t('aiWizard.summary.otherCampaigns'),
      otherCampaignPost: t('aiWizard.summary.otherCampaignPost'),
      existingStatus: t('aiWizard.summary.existingStatus'),
      published: t('aiWizard.summary.published'),
      publishedDate: t('aiWizard.summary.publishedDate'),
      scheduled: t('aiWizard.summary.scheduled'),
      processing: t('aiWizard.summary.processing'),
      readyToPublish: t('aiWizard.summary.readyToPublish'),
      failed: t('aiWizard.summary.failed'),
      draft: t('aiWizard.summary.draft'),
      viewPost: t('aiWizard.summary.viewPost'),
    },
    // Navigation
    nav: {
      previous: t('aiWizard.nav.previous'),
      next: t('aiWizard.nav.next'),
    },
    // WordPress translations for WpGateModal
    wordpress: {
      title: t('settings.wordpress.title'),
      connected: t('settings.wordpress.connected'),
      notConnected: t('settings.wordpress.notConnected'),
      connecting: t('settings.wordpress.connecting'),
      disconnected: t('settings.wordpress.disconnected'),
      error: t('settings.wordpress.error'),
      connectedDesc: t('settings.wordpress.connectedDesc'),
      connectingDesc: t('settings.wordpress.connectingDesc'),
      disconnectedDesc: t('settings.wordpress.disconnectedDesc'),
      errorDesc: t('settings.wordpress.errorDesc'),
      notConnectedDesc: t('settings.wordpress.notConnectedDesc'),
      downloadPlugin: t('settings.wordpress.downloadPlugin'),
      downloading: t('settings.wordpress.downloading'),
      autoInstall: t('settings.wordpress.autoInstall'),
      autoInstallTitle: t('settings.wordpress.autoInstallTitle'),
      autoInstallDesc: t('settings.wordpress.autoInstallDesc'),
      autoInstallSuccess: t('settings.wordpress.autoInstallSuccess'),
      autoInstallFailed: t('settings.wordpress.autoInstallFailed'),
      wpAdminUrl: t('settings.wordpress.wpAdminUrl'),
      wpUsername: t('settings.wordpress.wpUsername'),
      wpUsernamePlaceholder: t('settings.wordpress.wpUsernamePlaceholder'),
      wpPassword: t('settings.wordpress.wpPassword'),
      installing: t('settings.wordpress.installing'),
      installNow: t('settings.wordpress.installNow'),
      securityNote: t('settings.wordpress.securityNote'),
      connectionDetails: t('settings.wordpress.connectionDetails'),
      lastPing: t('settings.wordpress.lastPing'),
      pluginVersion: t('settings.wordpress.pluginVersion'),
      wpVersion: t('settings.wordpress.wpVersion'),
      siteKey: t('settings.wordpress.siteKey'),
      neverConnected: t('settings.wordpress.neverConnected'),
      justNow: t('settings.wordpress.justNow'),
      minutesAgo: t('settings.wordpress.minutesAgo'),
      hoursAgo: t('settings.wordpress.hoursAgo'),
      daysAgo: t('settings.wordpress.daysAgo'),
      howToInstall: t('settings.wordpress.howToInstall'),
      step1: t('settings.wordpress.step1'),
      step2: t('settings.wordpress.step2'),
      step3: t('settings.wordpress.step3'),
      step4: t('settings.wordpress.step4'),
      description: t('settings.wordpress.description'),
      disconnect: t('settings.wordpress.disconnect'),
      disconnecting: t('settings.wordpress.disconnecting'),
      disconnectConfirm: t('settings.wordpress.disconnectConfirm'),
      disconnectFailed: t('settings.wordpress.disconnectFailed'),
      errors: {
        restApiUnreachable: t('settings.wordpress.errors.restApiUnreachable'),
        restApiError: t('settings.wordpress.errors.restApiError'),
        authRequestFailed: t('settings.wordpress.errors.authRequestFailed'),
        authFailed: t('settings.wordpress.errors.authFailed'),
        insufficientPermissions: t('settings.wordpress.errors.insufficientPermissions'),
        pluginsApiUnavailable: t('settings.wordpress.errors.pluginsApiUnavailable'),
        activationFailed: t('settings.wordpress.errors.activationFailed'),
        manualInstallRequired: t('settings.wordpress.errors.manualInstallRequired'),
        unknownError: t('settings.wordpress.errors.unknownError'),
      },
    },
    // Campaign lifecycle actions
    campaigns: {
      activate: t('contentPlanner.campaigns.activate'),
      pause: t('contentPlanner.campaigns.pause'),
      resume: t('contentPlanner.campaigns.resume'),
      noPlan: t('contentPlanner.campaigns.noPlan'),
      activateConfirm: t('contentPlanner.campaigns.activateConfirm'),
    },
  };

  return (
    <div className={styles.container}>
      <div className={styles.pageHeader}>
        <div className={styles.headerContent}>
          <h1 className={styles.pageTitle}>{t('aiWizard.title')}</h1>
          <p className={styles.pageSubtitle}>{t('aiWizard.subtitle')}</p>
        </div>
      </div>

      <WizardContent translations={translations} />
    </div>
  );
}
