'use client';

import { useState, useCallback, useEffect, useRef } from 'react';
import { createPortal } from 'react-dom';
import {
  BookOpen, Sparkles, Loader2, RefreshCw, PenLine, Check,
  ChevronDown, Plus, X, Search as SearchIcon, AlertTriangle,
} from 'lucide-react';
import { useLocale } from '@/app/context/locale-context';
import { useSite } from '@/app/context/site-context';
import { ARTICLE_TYPE_KEY_MAP } from '../../wizardConfig';
import styles from '../../page.module.css';

export default function SubjectsStep({ state, dispatch, translations }) {
  const t = translations.subjects;
  const tTypes = translations.articleTypes.types;
  const { selectedSite } = useSite();
  const { locale } = useLocale();
  const [generating, setGenerating] = useState(false);
  const [error, setError] = useState(null);
  // Which keyword accordion is open (index or null)
  const [openKeyword, setOpenKeyword] = useState(0);
  // Which subject is expanded to show explanation (key: `${kwIdx}-${subjIdx}`)
  const [expandedSubject, setExpandedSubject] = useState(null);
  // Custom subject form state
  const [customTitle, setCustomTitle] = useState('');
  const [customExplanation, setCustomExplanation] = useState('');
  const [customArticleType, setCustomArticleType] = useState('');
  const [validationPopup, setValidationPopup] = useState(null);

  const totalKeywords = state.selectedKeywordIds.length + state.manualKeywords.length;
  const hasData = state.subjectSuggestions?.length > 0;
  const maxSelections = state.postsCount;
  const selectedCount = state.subjects.length;
  const canSelectMore = selectedCount < maxSelections;

  const handleGenerate = useCallback(async () => {
    if (!selectedSite?.id) return;
    setGenerating(true);
    setError(null);

    try {
      const res = await fetch('/api/campaigns/generate-subjects', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          siteId: selectedSite.id,
          selectedKeywordIds: state.selectedKeywordIds,
          manualKeywords: state.manualKeywords,
          articleTypes: state.articleTypes,
          postsCount: state.postsCount,
          locale,
        }),
      });

      if (!res.ok) {
        const data = await res.json();
        throw new Error(data.error || t.errorGenerating || 'Failed to generate');
      }

      const data = await res.json();
      const suggestions = data.suggestions || [];

      // Store AI suggestions separately, clear selections
      dispatch({ type: 'SET_FIELD', field: 'subjectSuggestions', value: suggestions });
      dispatch({ type: 'SET_FIELD', field: 'subjects', value: [] });
      setOpenKeyword(0);
    } catch (err) {
      console.error('Failed to generate subjects:', err);
      setError(err.message);
    } finally {
      setGenerating(false);
    }
  }, [selectedSite?.id, state.selectedKeywordIds, state.manualKeywords, state.articleTypes, state.postsCount, locale, dispatch]);

  // Auto-generate on first visit (no suggestions yet)
  const autoGenerated = useRef(false);
  useEffect(() => {
    if (!hasData && !autoGenerated.current && !generating && totalKeywords > 0) {
      autoGenerated.current = true;
      handleGenerate();
    }
  }, [hasData, generating, totalKeywords, handleGenerate]);

  // Check if a subject is selected
  const isSelected = (keyword, subjectIndex) => {
    return state.subjects.some(
      s => !s.isCustom && s.keyword === keyword && s.subjectIndex === subjectIndex
    );
  };

  // Toggle selection of an AI-generated subject
  const toggleSubject = (keyword, subjectIndex, subject) => {
    const existing = state.subjects.findIndex(
      s => !s.isCustom && s.keyword === keyword && s.subjectIndex === subjectIndex
    );

    if (existing >= 0) {
      // Deselect
      dispatch({
        type: 'SET_FIELD',
        field: 'subjects',
        value: state.subjects.filter((_, i) => i !== existing),
      });
    } else if (canSelectMore) {
      // Check if keyword already has a selected subject
      const keywordHasSelection = state.subjects.some(s => s.keyword === keyword);
      if (keywordHasSelection) {
        setValidationPopup(t.onePerKeyword);
        return;
      }
      // Select
      dispatch({
        type: 'SET_FIELD',
        field: 'subjects',
        value: [
          ...state.subjects,
          {
            keyword,
            subjectIndex,
            title: subject.title,
            explanation: subject.explanation,
            articleType: subject.articleType,
            isCustom: false,
          },
        ],
      });
    }
  };

  // Add a custom subject under a keyword
  const addCustomSubject = (keyword) => {
    if (!customTitle.trim() || !canSelectMore) return;
    // Check if keyword already has a selected subject
    const keywordHasSelection = state.subjects.some(s => s.keyword === keyword);
    if (keywordHasSelection) {
      setValidationPopup(t.onePerKeyword);
      return;
    }
    dispatch({
      type: 'SET_FIELD',
      field: 'subjects',
      value: [
        ...state.subjects,
        {
          keyword,
          subjectIndex: -1,
          title: customTitle.trim(),
          explanation: customExplanation.trim(),
          articleType: customArticleType || state.articleTypes[0]?.id || 'BLOG_POST',
          isCustom: true,
        },
      ],
    });
    setCustomTitle('');
    setCustomExplanation('');
    setCustomArticleType('');
  };

  // Remove a selected subject
  const removeSelected = (index) => {
    dispatch({
      type: 'SET_FIELD',
      field: 'subjects',
      value: state.subjects.filter((_, i) => i !== index),
    });
  };

  const toggleKeywordAccordion = (idx) => {
    setOpenKeyword(openKeyword === idx ? null : idx);
  };

  const toggleSubjectExpand = (key) => {
    setExpandedSubject(expandedSubject === key ? null : key);
  };

  // Update an AI suggestion's title or explanation
  const updateSuggestion = (kwIdx, subjIdx, field, value) => {
    const updated = state.subjectSuggestions.map((kw, ki) => {
      if (ki !== kwIdx) return kw;
      return {
        ...kw,
        subjects: kw.subjects.map((s, si) => {
          if (si !== subjIdx) return s;
          return { ...s, [field]: value };
        }),
      };
    });
    dispatch({ type: 'SET_FIELD', field: 'subjectSuggestions', value: updated });

    // Also update in selected subjects if this one is selected
    const keyword = state.subjectSuggestions[kwIdx].keyword;
    const selIdx = state.subjects.findIndex(
      s => !s.isCustom && s.keyword === keyword && s.subjectIndex === subjIdx
    );
    if (selIdx >= 0) {
      const updatedSubjects = [...state.subjects];
      updatedSubjects[selIdx] = { ...updatedSubjects[selIdx], [field]: value };
      dispatch({ type: 'SET_FIELD', field: 'subjects', value: updatedSubjects });
    }
  };

  const getArticleTypeLabel = (typeId) => {
    const key = ARTICLE_TYPE_KEY_MAP[typeId];
    return tTypes[key]?.label || typeId;
  };

  return (
    <div className={styles.stepContent}>
      <div className={styles.stepHeader}>
        <div className={styles.stepIconWrapper}>
          <BookOpen className={styles.stepHeaderIcon} />
        </div>
        <div className={styles.stepInfo}>
          <h2 className={styles.stepTitle}>{t.title}</h2>
          <p className={styles.stepDescription}>
            {t.description.replace('{max}', maxSelections)}
          </p>
        </div>
      </div>

      {/* No keywords warning */}
      {totalKeywords === 0 && (
        <div className={styles.subjectWarning}>
          {t.noKeywordsWarning}
        </div>
      )}

      {/* Selection counter */}
      {hasData && (
        <div className={styles.subjectCounter}>
          <span className={selectedCount >= maxSelections ? styles.subjectCountFull : ''}>
            {t.selectedCount
              .replace('{count}', selectedCount)
              .replace('{max}', maxSelections)}
          </span>
        </div>
      )}

      {/* Generate button */}
      {totalKeywords > 0 && (
        <button
          className={styles.generateSubjectsBtn}
          onClick={handleGenerate}
          disabled={generating}
        >
          {generating ? (
            <>
              <Loader2 size={18} className={styles.spinner} />
              {t.generating}
            </>
          ) : hasData ? (
            <>
              <RefreshCw size={18} />
              {t.regenerate}
            </>
          ) : (
            <>
              <Sparkles size={18} />
              {t.generate}
            </>
          )}
        </button>
      )}

      {/* Error message */}
      {error && (
        <div className={styles.subjectError}>
          {t.errorGenerating}
        </div>
      )}

      {/* Keywords accordion */}
      {hasData && (
        <div className={styles.subjectKeywordsList}>
          {state.subjectSuggestions.map((kwData, kwIdx) => {
            const isOpen = openKeyword === kwIdx;
            const kwSelectedCount = state.subjects.filter(s => s.keyword === kwData.keyword).length;

            return (
              <div
                key={kwIdx}
                className={`${styles.subjectKeywordItem} ${isOpen ? styles.subjectKeywordItemOpen : ''}`}
              >
                {/* Keyword accordion header */}
                <button
                  className={styles.subjectKeywordHeader}
                  onClick={() => toggleKeywordAccordion(kwIdx)}
                >
                  <SearchIcon size={16} className={styles.subjectKeywordIcon} />
                  <span className={styles.subjectKeywordLabel}>{kwData.keyword}</span>
                  {kwSelectedCount > 0 && (
                    <span className={styles.subjectKeywordBadge}>{kwSelectedCount}</span>
                  )}
                  <ChevronDown
                    size={16}
                    className={`${styles.subjectKeywordChevron} ${isOpen ? styles.subjectKeywordChevronOpen : ''}`}
                  />
                </button>

                {/* Keyword accordion body */}
                {isOpen && (
                  <div className={styles.subjectKeywordBody}>
                    {/* AI-generated subjects */}
                    {kwData.subjects.map((subj, subjIdx) => {
                      const selected = isSelected(kwData.keyword, subjIdx);
                      const expandKey = `${kwIdx}-${subjIdx}`;
                      const isExpanded = expandedSubject === expandKey;
                      const disabled = !selected && !canSelectMore;

                      return (
                        <div
                          key={subjIdx}
                          className={`${styles.subjectSuggestion} ${selected ? styles.subjectSuggestionSelected : ''} ${disabled ? styles.subjectSuggestionDisabled : ''}`}
                        >
                          <div className={styles.subjectSuggestionMain}>
                            <button
                              className={styles.subjectCheckBtn}
                              onClick={() => toggleSubject(kwData.keyword, subjIdx, subj)}
                              disabled={disabled}
                            >
                              <span className={`${styles.subjectCheckbox} ${selected ? styles.subjectCheckboxChecked : ''}`}>
                                {selected && <Check size={12} />}
                              </span>
                            </button>
                            <div
                              className={styles.subjectSuggestionContent}
                              onClick={() => toggleSubjectExpand(expandKey)}
                            >
                              <span className={styles.subjectSuggestionTitle}>{subj.title}</span>
                              <span className={styles.subjectSuggestionTypeBadge}>
                                {getArticleTypeLabel(subj.articleType)}
                              </span>
                            </div>
                            <button
                              className={`${styles.subjectExpandBtn} ${isExpanded ? styles.subjectExpandBtnOpen : ''}`}
                              onClick={() => toggleSubjectExpand(expandKey)}
                            >
                              <ChevronDown size={14} />
                            </button>
                          </div>

                          {isExpanded && (
                            <div className={styles.subjectExplanation}>
                              <input
                                type="text"
                                className={styles.subjectEditTitle}
                                value={subj.title}
                                onChange={(e) => updateSuggestion(kwIdx, subjIdx, 'title', e.target.value)}
                                onClick={(e) => e.stopPropagation()}
                              />
                              <textarea
                                className={styles.subjectEditExplanation}
                                value={subj.explanation}
                                onChange={(e) => updateSuggestion(kwIdx, subjIdx, 'explanation', e.target.value)}
                                onClick={(e) => e.stopPropagation()}
                                rows={2}
                              />
                              <span className={styles.subjectExplanationType}>
                                {getArticleTypeLabel(subj.articleType)}
                              </span>
                            </div>
                          )}
                        </div>
                      );
                    })}

                    {/* Custom subject form */}
                    <div className={styles.subjectCustomForm}>
                      <div className={styles.subjectCustomFormHeader}>
                        <PenLine size={14} />
                        <span>{t.addCustom}</span>
                      </div>
                      <input
                        type="text"
                        className={styles.subjectCustomInput}
                        value={customTitle}
                        onChange={(e) => setCustomTitle(e.target.value)}
                        placeholder={t.customPlaceholder}
                      />
                      <textarea
                        className={styles.subjectCustomTextarea}
                        value={customExplanation}
                        onChange={(e) => setCustomExplanation(e.target.value)}
                        placeholder={t.explanationPlaceholder}
                        rows={2}
                      />
                      <div className={styles.subjectCustomActions}>
                        <select
                          className={styles.subjectCustomSelect}
                          value={customArticleType || state.articleTypes[0]?.id || ''}
                          onChange={(e) => setCustomArticleType(e.target.value)}
                        >
                          {state.articleTypes.map(at => (
                            <option key={at.id} value={at.id}>
                              {getArticleTypeLabel(at.id)}
                            </option>
                          ))}
                        </select>
                        <button
                          className={styles.subjectCustomAddBtn}
                          onClick={() => addCustomSubject(kwData.keyword)}
                          disabled={!customTitle.trim() || !canSelectMore}
                        >
                          <Plus size={14} />
                          {t.addSubject}
                        </button>
                      </div>
                    </div>
                  </div>
                )}
              </div>
            );
          })}
        </div>
      )}

      {/* Selected subjects summary */}
      {selectedCount > 0 && (
        <div className={styles.subjectSelectedSection}>
          <h4 className={styles.subjectSelectedTitle}>{t.selectedSubjects}</h4>
          <div className={styles.subjectSelectedList}>
            {state.subjects.map((subj, idx) => (
              <div key={idx} className={styles.subjectSelectedItem}>
                <div className={styles.subjectSelectedInfo}>
                  <span className={styles.subjectSelectedItemTitle}>{subj.title}</span>
                  <span className={styles.subjectSelectedItemMeta}>
                    {subj.keyword} · {getArticleTypeLabel(subj.articleType)}
                    {subj.isCustom && ` · ${t.custom}`}
                  </span>
                </div>
                <button
                  className={styles.subjectSelectedRemove}
                  onClick={() => removeSelected(idx)}
                >
                  <X size={14} />
                </button>
              </div>
            ))}
          </div>
        </div>
      )}

      {/* Status */}
      {hasData && (
        <div className={styles.subjectStatus}>
          {selectedCount >= maxSelections ? (
            <span className={styles.subjectStatusComplete}>
              <Check size={14} />
              {t.allSelected}
            </span>
          ) : (
            <span className={styles.subjectStatusIncomplete}>
              {t.selectRemaining.replace('{count}', maxSelections - selectedCount)}
            </span>
          )}
        </div>
      )}

      {/* One-per-keyword validation popup */}
      {validationPopup && createPortal(
        <div className={styles.modalOverlay} onClick={() => setValidationPopup(null)}>
          <div className={styles.validationPopup} onClick={(e) => e.stopPropagation()}>
            <button className={styles.validationPopupClose} onClick={() => setValidationPopup(null)}>
              <X size={18} />
            </button>
            <div className={styles.validationPopupIcon}>
              <AlertTriangle size={28} />
            </div>
            <p className={styles.validationPopupMessage}>{validationPopup}</p>
            <button className={styles.validationPopupBtn} onClick={() => setValidationPopup(null)}>
              {t.gotIt}
            </button>
          </div>
        </div>,
        document.body
      )}
    </div>
  );
}
