'use client';

import { useState, useCallback, useEffect, useRef } from 'react';
import {
  BookOpen, Sparkles, Loader2, RefreshCw, PenLine, Check,
  ChevronDown, Plus, X, BrainCircuit,
} from 'lucide-react';
import { useLocale } from '@/app/context/locale-context';
import { useSite } from '@/app/context/site-context';
import { ARTICLE_TYPE_KEY_MAP, translateIntent } from '../../wizardConfig';
import styles from '../../page.module.css';

export default function SubjectsStep({ state, dispatch, translations }) {
  const t = translations.subjects;
  const tTypes = translations.articleTypes.types;
  const intentsMap = t.intents || {};
  const { selectedSite } = useSite();
  const { locale } = useLocale();
  const [generating, setGenerating] = useState(false);
  const [error, setError] = useState(null);
  const [expandedSubject, setExpandedSubject] = useState(null);
  const [customTitle, setCustomTitle] = useState('');
  const [customExplanation, setCustomExplanation] = useState('');
  const [customArticleType, setCustomArticleType] = useState('');
  const [recommending, setRecommending] = useState(false);
  const [recommendation, setRecommendation] = useState(null); // { explanation }
  const prevLocaleRef = useRef(locale);

  const hasData = state.subjectSuggestions?.length > 0;
  const maxSelections = state.postsCount;
  const selectedCount = state.subjects.length;
  const canSelectMore = selectedCount < maxSelections;
  const hasMainKeyword = !!state.mainKeyword?.trim();

  const handleGenerate = useCallback(async () => {
    if (!selectedSite?.id || !hasMainKeyword) return;
    setGenerating(true);
    setError(null);
    setRecommendation(null);

    // Clear previous suggestions when regenerating
    dispatch({ type: 'SET_FIELD', field: 'subjectSuggestions', value: [] });
    dispatch({ type: 'SET_FIELD', field: 'subjects', value: [] });

    try {
      const res = await fetch('/api/campaigns/generate-subjects', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          siteId: selectedSite.id,
          mainKeyword: state.mainKeyword,
          pillarPageUrl: state.pillarPageUrl || '',
          articleTypes: state.articleTypes,
          postsCount: state.postsCount,
          locale,
        }),
      });

      if (!res.ok) {
        const data = await res.json();
        throw new Error(data.error || t.errorGenerating || 'Failed to generate');
      }

      // Parse SSE stream
      const reader = res.body.getReader();
      const decoder = new TextDecoder();
      const collected = [];
      let buffer = '';

      while (true) {
        const { done, value } = await reader.read();
        if (done) break;

        buffer += decoder.decode(value, { stream: true });
        const lines = buffer.split('\n');
        buffer = lines.pop() || '';

        for (const line of lines) {
          const trimmed = line.trim();
          if (!trimmed.startsWith('data: ')) continue;
          const payload = trimmed.slice(6);
          if (payload === '[DONE]') continue;

          try {
            const parsed = JSON.parse(payload);
            if (parsed.error) {
              throw new Error(parsed.error);
            }
            collected.push(parsed);
            dispatch({ type: 'SET_FIELD', field: 'subjectSuggestions', value: [...collected] });
          } catch (parseErr) {
            if (parseErr.message && !parseErr.message.includes('JSON')) {
              throw parseErr;
            }
          }
        }
      }
    } catch (err) {
      console.error('Failed to generate subjects:', err);
      setError(err.message);
    } finally {
      setGenerating(false);
    }
  }, [selectedSite?.id, state.mainKeyword, state.pillarPageUrl, state.articleTypes, state.postsCount, locale, dispatch, hasMainKeyword, t.errorGenerating]);

  // Auto-generate on first visit (no suggestions yet)
  const autoGenerated = useRef(false);
  useEffect(() => {
    if (!hasData && !autoGenerated.current && !generating && hasMainKeyword) {
      autoGenerated.current = true;
      handleGenerate();
    }
  }, [hasData, generating, hasMainKeyword, handleGenerate]);

  // Ask AI to recommend the best subjects and auto-select them
  const handleRecommend = useCallback(async (subjects, currentLocale) => {
    if (!subjects?.length || !state.mainKeyword) return;
    setRecommending(true);

    try {
      const res = await fetch('/api/campaigns/recommend-subjects', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          mainKeyword: state.mainKeyword,
          subjects,
          postsCount: state.postsCount,
          locale: currentLocale,
        }),
      });

      if (!res.ok) return;

      const data = await res.json();
      setRecommendation({ explanation: data.explanation });

      // Auto-select the recommended subjects (only if user hasn't manually selected any)
      if (state.subjects.length === 0 && data.recommendedIndices?.length > 0) {
        const selected = data.recommendedIndices
          .filter(i => i >= 0 && i < subjects.length)
          .map(i => ({
            subjectIndex: i,
            title: subjects[i].title,
            explanation: subjects[i].explanation,
            articleType: subjects[i].articleType,
            intent: subjects[i].intent || '',
            isCustom: false,
          }));
        dispatch({ type: 'SET_FIELD', field: 'subjects', value: selected });
      }
    } catch (err) {
      console.error('Failed to get recommendation:', err);
    } finally {
      setRecommending(false);
    }
  }, [state.mainKeyword, state.postsCount, state.subjects.length, dispatch]);

  // Auto-recommend after generation completes
  const prevGenerating = useRef(false);
  useEffect(() => {
    if (prevGenerating.current && !generating && hasData) {
      handleRecommend(state.subjectSuggestions, locale);
    }
    prevGenerating.current = generating;
  }, [generating, hasData, state.subjectSuggestions, locale, handleRecommend]);

  // Re-fetch recommendation when locale changes (cached in DB per locale)
  useEffect(() => {
    if (prevLocaleRef.current !== locale && hasData && !generating) {
      prevLocaleRef.current = locale;
      handleRecommend(state.subjectSuggestions, locale);
    }
  }, [locale, hasData, generating, state.subjectSuggestions, handleRecommend]);

  const isSelected = (subjIdx) => {
    return state.subjects.some(s => !s.isCustom && s.subjectIndex === subjIdx);
  };

  const toggleSubject = (subjIdx, subject) => {
    const existing = state.subjects.findIndex(s => !s.isCustom && s.subjectIndex === subjIdx);

    if (existing >= 0) {
      dispatch({
        type: 'SET_FIELD',
        field: 'subjects',
        value: state.subjects.filter((_, i) => i !== existing),
      });
    } else if (canSelectMore) {
      dispatch({
        type: 'SET_FIELD',
        field: 'subjects',
        value: [
          ...state.subjects,
          {
            subjectIndex: subjIdx,
            title: subject.title,
            explanation: subject.explanation,
            articleType: subject.articleType,
            intent: subject.intent || '',
            isCustom: false,
          },
        ],
      });
    }
  };

  const addCustomSubject = () => {
    if (!customTitle.trim() || !canSelectMore) return;
    dispatch({
      type: 'SET_FIELD',
      field: 'subjects',
      value: [
        ...state.subjects,
        {
          subjectIndex: -1,
          title: customTitle.trim(),
          explanation: customExplanation.trim(),
          articleType: customArticleType || state.articleTypes[0]?.id || 'BLOG_POST',
          intent: '',
          isCustom: true,
        },
      ],
    });
    setCustomTitle('');
    setCustomExplanation('');
    setCustomArticleType('');
  };

  const removeSelected = (index) => {
    dispatch({
      type: 'SET_FIELD',
      field: 'subjects',
      value: state.subjects.filter((_, i) => i !== index),
    });
  };

  const toggleSubjectExpand = (key) => {
    setExpandedSubject(expandedSubject === key ? null : key);
  };

  const updateSuggestion = (subjIdx, field, value) => {
    const updated = state.subjectSuggestions.map((s, i) => {
      if (i !== subjIdx) return s;
      return { ...s, [field]: value };
    });
    dispatch({ type: 'SET_FIELD', field: 'subjectSuggestions', value: updated });

    const selIdx = state.subjects.findIndex(s => !s.isCustom && s.subjectIndex === subjIdx);
    if (selIdx >= 0) {
      const updatedSubjects = [...state.subjects];
      updatedSubjects[selIdx] = { ...updatedSubjects[selIdx], [field]: value };
      dispatch({ type: 'SET_FIELD', field: 'subjects', value: updatedSubjects });
    }
  };

  const getArticleTypeLabel = (typeId) => {
    const key = ARTICLE_TYPE_KEY_MAP[typeId];
    return tTypes[key]?.label || typeId;
  };

  return (
    <div className={styles.stepContent}>
      <div className={styles.stepHeader}>
        <div className={styles.stepIconWrapper}>
          <BookOpen className={styles.stepHeaderIcon} />
        </div>
        <div className={styles.stepInfo}>
          <h2 className={styles.stepTitle}>{t.title}</h2>
          <p className={styles.stepDescription}>
            {t.description.replace('{max}', maxSelections)}
          </p>
        </div>
      </div>

      {/* No main keyword warning */}
      {!hasMainKeyword && (
        <div className={styles.subjectWarning}>
          {t.noMainKeywordWarning}
        </div>
      )}

      {/* Selection counter */}
      {hasData && (
        <div className={styles.subjectCounter}>
          <span className={selectedCount >= maxSelections ? styles.subjectCountFull : ''}>
            {t.selectedCount
              .replace('{count}', selectedCount)
              .replace('{max}', maxSelections)}
          </span>
        </div>
      )}

      {/* Generate button */}
      {hasMainKeyword && (
        <button
          className={styles.generateSubjectsBtn}
          onClick={handleGenerate}
          disabled={generating}
        >
          {generating ? (
            <>
              <Loader2 size={18} className={styles.spinner} />
              {t.generating}
            </>
          ) : hasData ? (
            <>
              <RefreshCw size={18} />
              {t.regenerate}
            </>
          ) : (
            <>
              <Sparkles size={18} />
              {t.generate}
            </>
          )}
        </button>
      )}

      {/* Error message */}
      {error && (
        <div className={styles.subjectError}>
          {t.errorGenerating}
        </div>
      )}

      {/* AI recommendation banner */}
      {recommending && (
        <div className={styles.aiRecommendationBanner}>
          <Loader2 size={16} className={styles.spinner} />
          <span>{t.aiRecommending || 'AI is choosing the best subjects...'}</span>
        </div>
      )}
      {recommendation && !recommending && (
        <div className={styles.aiRecommendationBanner}>
          <BrainCircuit size={16} className={styles.aiRecommendationIcon} />
          <span>{recommendation.explanation}</span>
        </div>
      )}

      {/* Flat suggestions list */}
      {hasData && (
        <div className={styles.subjectFlatList}>
          {state.subjectSuggestions.map((subj, subjIdx) => {
            const selected = isSelected(subjIdx);
            const isExpanded = expandedSubject === subjIdx;
            const disabled = !selected && !canSelectMore;

            return (
              <div
                key={subjIdx}
                className={`${styles.subjectSuggestion} ${selected ? styles.subjectSuggestionSelected : ''} ${disabled ? styles.subjectSuggestionDisabled : ''}`}
              >
                <div className={styles.subjectSuggestionMain}>
                  <button
                    className={styles.subjectCheckBtn}
                    onClick={() => toggleSubject(subjIdx, subj)}
                    disabled={disabled}
                  >
                    <span className={`${styles.subjectCheckbox} ${selected ? styles.subjectCheckboxChecked : ''}`}>
                      {selected && <Check size={12} />}
                    </span>
                  </button>
                  <div
                    className={styles.subjectSuggestionContent}
                    onClick={() => toggleSubjectExpand(subjIdx)}
                  >
                    <span className={styles.subjectSuggestionTitle}>{subj.title}</span>
                    <div className={styles.subjectSuggestionBadges}>
                      <span className={styles.subjectSuggestionTypeBadge}>
                        {getArticleTypeLabel(subj.articleType)}
                      </span>
                      {subj.intent && (
                        <span className={styles.subjectIntentBadge}>
                          {translateIntent(subj.intent, intentsMap)}
                        </span>
                      )}
                    </div>
                  </div>
                  <button
                    className={`${styles.subjectExpandBtn} ${isExpanded ? styles.subjectExpandBtnOpen : ''}`}
                    onClick={() => toggleSubjectExpand(subjIdx)}
                  >
                    <ChevronDown size={14} />
                  </button>
                </div>

                {isExpanded && (
                  <div className={styles.subjectExplanation}>
                    <input
                      type="text"
                      className={styles.subjectEditTitle}
                      value={subj.title}
                      onChange={(e) => updateSuggestion(subjIdx, 'title', e.target.value)}
                      onClick={(e) => e.stopPropagation()}
                    />
                    <textarea
                      className={styles.subjectEditExplanation}
                      value={subj.explanation}
                      onChange={(e) => updateSuggestion(subjIdx, 'explanation', e.target.value)}
                      onClick={(e) => e.stopPropagation()}
                      rows={2}
                    />
                    <div className={styles.subjectExplanationMeta}>
                      <span className={styles.subjectExplanationType}>
                        {getArticleTypeLabel(subj.articleType)}
                      </span>
                      {subj.intent && (
                        <span className={styles.subjectIntentBadge}>
                          {translateIntent(subj.intent, intentsMap)}
                        </span>
                      )}
                    </div>
                  </div>
                )}
              </div>
            );
          })}
        </div>
      )}

      {/* Custom subject form */}
      {hasData && (
        <div className={styles.subjectCustomForm}>
          <div className={styles.subjectCustomFormHeader}>
            <PenLine size={14} />
            <span>{t.addCustom}</span>
          </div>
          <input
            type="text"
            className={styles.subjectCustomInput}
            value={customTitle}
            onChange={(e) => setCustomTitle(e.target.value)}
            placeholder={t.customPlaceholder}
          />
          <textarea
            className={styles.subjectCustomTextarea}
            value={customExplanation}
            onChange={(e) => setCustomExplanation(e.target.value)}
            placeholder={t.explanationPlaceholder}
            rows={2}
          />
          <div className={styles.subjectCustomActions}>
            <select
              className={styles.subjectCustomSelect}
              value={customArticleType || state.articleTypes[0]?.id || ''}
              onChange={(e) => setCustomArticleType(e.target.value)}
            >
              {state.articleTypes.map(at => (
                <option key={at.id} value={at.id}>
                  {getArticleTypeLabel(at.id)}
                </option>
              ))}
            </select>
            <button
              className={styles.subjectCustomAddBtn}
              onClick={addCustomSubject}
              disabled={!customTitle.trim() || !canSelectMore}
            >
              <Plus size={14} />
              {t.addSubject}
            </button>
          </div>
        </div>
      )}

      {/* Selected subjects summary */}
      {selectedCount > 0 && (
        <div className={styles.subjectSelectedSection}>
          <h4 className={styles.subjectSelectedTitle}>{t.selectedSubjects}</h4>
          <div className={styles.subjectSelectedList}>
            {state.subjects.map((subj, idx) => (
              <div key={idx} className={styles.subjectSelectedItem}>
                <div className={styles.subjectSelectedInfo}>
                  <span className={styles.subjectSelectedItemTitle}>{subj.title}</span>
                  <span className={styles.subjectSelectedItemMeta}>
                    {getArticleTypeLabel(subj.articleType)}
                    {subj.intent && ` \u00b7 ${translateIntent(subj.intent, intentsMap)}`}
                    {subj.isCustom && ` \u00b7 ${t.custom}`}
                  </span>
                </div>
                <button
                  className={styles.subjectSelectedRemove}
                  onClick={() => removeSelected(idx)}
                >
                  <X size={14} />
                </button>
              </div>
            ))}
          </div>
        </div>
      )}

      {/* Status */}
      {hasData && (
        <div className={styles.subjectStatus}>
          {selectedCount >= maxSelections ? (
            <span className={styles.subjectStatusComplete}>
              <Check size={14} />
              {t.allSelected}
            </span>
          ) : (
            <span className={styles.subjectStatusIncomplete}>
              {t.selectRemaining.replace('{count}', maxSelections - selectedCount)}
            </span>
          )}
        </div>
      )}
    </div>
  );
}
