/**
 * Send Report API
 * 
 * POST /api/reports/send
 * 
 * Sends a generated report to recipients via email.
 */

import { NextResponse } from 'next/server';
import prisma from '@/lib/prisma';
import { sendEmail } from '@/lib/mailer';
import { getAuthSession } from '@/lib/auth-permissions';
import { hasPermission, CAPABILITIES } from '@/lib/permissions';
import { getDefaultBranding } from '@/lib/reports/pdf-generator';

/**
 * Get email translations
 */
function getEmailTranslations(locale = 'en') {
  const translations = {
    en: {
      subject: '{siteName} Performance Report - {month}',
      title: 'Your SEO Performance Report is Ready',
      greeting: 'Hello,',
      body: 'Your monthly SEO performance report for <strong>{siteName}</strong> is now available. This report covers <strong>{month}</strong> and includes your site\'s health progression, automated optimizations, and our analysis.',
      downloadButton: 'Download Report (PDF)',
      questions: 'If you have any questions about this report or would like to discuss next steps, please don\'t hesitate to reach out.',
      generatedBy: 'This report was generated by',
      defaultAgencyName: 'Your SEO Agency',
      yourWebsite: 'Your Website',
    },
    he: {
      subject: 'דוח ביצועים {siteName} - {month}',
      title: 'דוח ביצועי ה-SEO שלך מוכן',
      greeting: 'שלום,',
      body: 'דוח ביצועי ה-SEO החודשי עבור <strong>{siteName}</strong> זמין כעת. דוח זה מכסה את <strong>{month}</strong> וכולל את התקדמות בריאות האתר שלך, אופטימיזציות אוטומטיות והניתוח שלנו.',
      downloadButton: 'הורד דוח (PDF)',
      questions: 'אם יש לך שאלות לגבי דוח זה או שתרצה לדון בצעדים הבאים, אל תהסס ליצור קשר.',
      generatedBy: 'דוח זה נוצר על ידי',
      defaultAgencyName: 'סוכנות ה-SEO שלך',
      yourWebsite: 'האתר שלך',
    },
  };
  return translations[locale] || translations.en;
}

/**
 * Generate email HTML for report delivery
 */
function generateReportEmailHtml({ branding, siteName, month, pdfUrl, locale = 'en' }) {
  const t = getEmailTranslations(locale);
  const primaryColor = branding?.primaryColor || '#7b2cbf';
  const agencyName = branding?.agencyName || t.defaultAgencyName;
  const direction = locale === 'he' ? 'rtl' : 'ltr';
  const textAlign = locale === 'he' ? 'right' : 'left';
  
  // Replace placeholders in body text
  const bodyText = t.body
    .replace('{siteName}', siteName)
    .replace('{month}', month);
  
  return `
<!DOCTYPE html>
<html dir="${direction}">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<body style="margin: 0; padding: 0; font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, sans-serif; background-color: #f5f5f5; direction: ${direction};">
  <table width="100%" cellpadding="0" cellspacing="0" style="background-color: #f5f5f5; padding: 40px 20px;">
    <tr>
      <td align="center">
        <table width="600" cellpadding="0" cellspacing="0" style="background-color: #ffffff; border-radius: 12px; overflow: hidden; box-shadow: 0 4px 6px rgba(0, 0, 0, 0.1);">
          <!-- Header -->
          <tr>
            <td style="background-color: ${primaryColor}; padding: 30px; text-align: center;">
              ${branding?.logoUrl 
                ? `<img src="${branding.logoUrl}" alt="${agencyName}" style="max-width: 150px; max-height: 50px;" />`
                : `<h1 style="color: #ffffff; margin: 0; font-size: 24px; font-weight: 600;">${agencyName}</h1>`
              }
            </td>
          </tr>
          
          <!-- Content -->
          <tr>
            <td style="padding: 40px 30px; text-align: ${textAlign};">
              <h2 style="color: #1a1a2e; margin: 0 0 20px; font-size: 22px; font-weight: 600;">
                ${t.title}
              </h2>
              
              <p style="color: #4b5563; font-size: 16px; line-height: 1.6; margin: 0 0 20px;">
                ${t.greeting}
              </p>
              
              <p style="color: #4b5563; font-size: 16px; line-height: 1.6; margin: 0 0 20px;">
                ${bodyText}
              </p>
              
              <!-- CTA Button -->
              <table width="100%" cellpadding="0" cellspacing="0" style="margin: 30px 0;">
                <tr>
                  <td align="center">
                    <a href="${pdfUrl}" 
                       style="display: inline-block; background-color: ${primaryColor}; color: #ffffff; 
                              text-decoration: none; padding: 14px 32px; border-radius: 8px; 
                              font-size: 16px; font-weight: 600;">
                      ${t.downloadButton}
                    </a>
                  </td>
                </tr>
              </table>
              
              <p style="color: #6b7280; font-size: 14px; line-height: 1.6; margin: 20px 0 0;">
                ${t.questions}
              </p>
            </td>
          </tr>
          
          <!-- Footer -->
          <tr>
            <td style="background-color: #f9fafb; padding: 20px 30px; border-top: 1px solid #e5e7eb;">
              <p style="color: #9ca3af; font-size: 12px; margin: 0; text-align: center;">
                ${t.generatedBy} ${agencyName}
                ${branding?.replyToEmail ? `<br><a href="mailto:${branding.replyToEmail}" style="color: ${primaryColor};">${branding.replyToEmail}</a>` : ''}
              </p>
            </td>
          </tr>
        </table>
      </td>
    </tr>
  </table>
</body>
</html>`;
}

/**
 * POST /api/reports/send
 * 
 * Body: { reportId: string, recipients?: string[] }
 */
export async function POST(request) {
  try {
    const session = await getAuthSession();
    if (!session?.member) {
      return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });
    }
    
    // Check permission
    if (!hasPermission(session.member, 'REPORTS', 'MANAGE')) {
      return NextResponse.json({ error: 'Permission denied' }, { status: 403 });
    }
    
    const body = await request.json();
    const { reportId, recipients: overrideRecipients } = body;
    
    if (!reportId) {
      return NextResponse.json({ error: 'reportId is required' }, { status: 400 });
    }
    
    // Fetch report with account info
    const report = await prisma.reportArchive.findUnique({
      where: { id: reportId },
      include: {
        account: true,
      },
    });
    
    if (!report) {
      return NextResponse.json({ error: 'Report not found' }, { status: 404 });
    }
    
    // Verify access
    if (report.accountId !== session.member.accountId) {
      return NextResponse.json({ error: 'Access denied' }, { status: 403 });
    }
    
    // Get site info
    const site = await prisma.site.findUnique({
      where: { id: report.siteId },
      select: { name: true, url: true },
    });
    
    // Determine recipients
    const recipients = overrideRecipients?.length > 0 
      ? overrideRecipients 
      : report.recipients;
    
    if (!recipients?.length) {
      return NextResponse.json({ error: 'No recipients specified' }, { status: 400 });
    }
    
    // Get branding - map whiteLabelConfig fields to branding fields
    const whiteLabelConfig = report.account?.whiteLabelConfig || {};
    const branding = {
      ...getDefaultBranding(),
      logoUrl: whiteLabelConfig.agencyLogo || null,
      agencyName: report.account?.name || '',
      primaryColor: whiteLabelConfig.accentColor || '#7b2cbf',
      replyToEmail: whiteLabelConfig.replyToEmail || '',
    };
    
    const agencyName = branding.agencyName || 'Your SEO Agency';
    
    // Determine locale (from request body or default to 'en')
    const locale = body.locale || 'en';
    const emailTranslations = getEmailTranslations(locale);
    
    // Generate email content
    const emailHtml = generateReportEmailHtml({
      branding,
      siteName: site?.name || emailTranslations.yourWebsite,
      month: report.month,
      pdfUrl: report.pdfUrl,
      locale,
    });
    
    // Generate subject line with translations
    const emailSubject = emailTranslations.subject
      .replace('{siteName}', site?.name || 'SEO')
      .replace('{month}', report.month);
    
    // Send emails
    const results = [];
    for (const recipient of recipients) {
      try {
        const result = await sendEmail({
          to: recipient,
          subject: emailSubject,
          html: emailHtml,
          from: branding.replyToEmail || undefined,
        });
        results.push({ email: recipient, success: result.success, error: result.error });
      } catch (error) {
        results.push({ email: recipient, success: false, error: error.message });
      }
    }
    
    const allSuccessful = results.every(r => r.success);
    const anySuccessful = results.some(r => r.success);
    
    // Update report status
    await prisma.reportArchive.update({
      where: { id: reportId },
      data: {
        status: allSuccessful ? 'SENT' : anySuccessful ? 'SENT' : 'ERROR',
        sentAt: anySuccessful ? new Date() : undefined,
        recipients,
        error: allSuccessful ? null : results.filter(r => !r.success).map(r => `${r.email}: ${r.error}`).join('; '),
      },
    });
    
    console.log(`[ReportSend] Sent report ${reportId} to ${recipients.length} recipients`);
    
    return NextResponse.json({
      success: anySuccessful,
      results,
      status: allSuccessful ? 'SENT' : anySuccessful ? 'PARTIAL' : 'ERROR',
    });
    
  } catch (error) {
    console.error('[ReportSend] Error:', error);
    return NextResponse.json({ 
      error: 'Failed to send report',
      details: error.message,
    }, { status: 500 });
  }
}
